# Generated by Django 5.0.7 on 2024-07-31 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('online_shop', '0004_alter_catagory_options_rename_content_comment_body_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='user',
            new_name='name',
        ),
    ]
