# Generated by Django 5.0.7 on 2024-07-31 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_shop', '0005_rename_user_order_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_provide',
            field=models.BooleanField(default=False),
        ),
    ]
